/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.seguidordecarrera.panels;

import com.mycompany.seguidordecarrera.Materia;
import com.mycompany.seguidordecarrera.Seguidor;
import java.util.Iterator;
import java.util.ArrayList;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivan
 */
public class matModifPanel extends javax.swing.JFrame {

    ArrayList<Materia> newCorrelat = new ArrayList();
    ArrayList<Materia> mats = new ArrayList();
    Materia matActual;
    AdminPanel admPanel;
    
    

    public matModifPanel() {
        initComponents();
        agregarRadioButtons();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbModPanel = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbNommat = new javax.swing.JLabel();
        cbCorrelativas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnAddCorrelativa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCorrelativas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnModCerrar = new javax.swing.JButton();
        btnModGuardar = new javax.swing.JButton();
        txtModCodigo = new javax.swing.JTextField();
        txtModNombre = new javax.swing.JTextField();
        cbModNivel = new javax.swing.JComboBox<>();
        rbFirma = new javax.swing.JRadioButton();
        rbAprob = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbNommat.setText("jLabel1");

        cbCorrelativas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel1.setText("Correlativa:");

        btnAddCorrelativa.setText("Agregar");
        btnAddCorrelativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCorrelativaActionPerformed(evt);
            }
        });

        tbCorrelativas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nivel", "Materia", "Codigo"
            }
        ));
        jScrollPane1.setViewportView(tbCorrelativas);

        jLabel2.setText("Nombre");

        jLabel3.setText("Nivel");

        jLabel4.setText("Codigo");

        btnModCerrar.setText("Cerrar");
        btnModCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModCerrarActionPerformed(evt);
            }
        });

        btnModGuardar.setText("Guardar");
        btnModGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModGuardarActionPerformed(evt);
            }
        });

        txtModCodigo.setText("");

        txtModNombre.setText("");

        cbModNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"1", "2", "3", "4", "5" }));

        rbFirma.setText("Firma");
        rbFirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFirmaActionPerformed(evt);
            }
        });

        rbAprob.setText("Aprobada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnModCerrar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbCorrelativas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtModNombre)
                                        .addComponent(txtModCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                        .addComponent(cbModNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(rbFirma)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rbAprob)
                                    .addGap(22, 22, 22)
                                    .addComponent(btnAddCorrelativa))
                                .addComponent(btnModGuardar)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(195, 195, 195)
                            .addComponent(lbNommat))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbNommat)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtModCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cbModNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbCorrelativas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddCorrelativa)
                            .addComponent(rbFirma)
                            .addComponent(rbAprob))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModCerrar)
                    .addComponent(btnModGuardar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void datosDeCampos(Materia unaMat, AdminPanel unPanel) {
        matActual = unaMat;
        admPanel = unPanel;
        txtModCodigo.setText(unaMat.getCodigo());
        txtModNombre.setText(unaMat.getNombre());
        cbModNivel.addItem(unaMat.getNivel());
        cbModNivel.setSelectedItem(unaMat.getNivel());
        cbCorrelativas.setSelectedItem("Seleccione una Correlativa");
        mats = unPanel.getMatList();
        Materia element;
        Iterator<Materia> it = mats.iterator();
        while (it.hasNext()) {
            element = it.next();
            cbCorrelativas.addItem(element.getNombre());
        }

    }

    private void rbFirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFirmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFirmaActionPerformed

    private void btnModGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModGuardarActionPerformed
        if (matActual.getNombre() != txtModNombre.getText() || matActual.getCodigo() != txtModCodigo.getText() || matActual.getNivel() != cbModNivel.getSelectedItem()) {
            matActual.setCodigo(txtModCodigo.getText());
            matActual.setNombre(txtModNombre.getText());
            matActual.setNivel(cbModNivel.getSelectedItem().toString());
            if(this.newCorrelat != null){
            newCorrelat.stream().forEach(m->matActual.AgregarCorrelativa(m));     
            }
            admPanel.actualizarTabla(matActual);
            dispose();
        }
    }//GEN-LAST:event_btnModGuardarActionPerformed

    private void btnModCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModCerrarActionPerformed

    }//GEN-LAST:event_btnModCerrarActionPerformed

    private void btnAddCorrelativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCorrelativaActionPerformed
       DefaultTableModel tbAux = (DefaultTableModel) tbCorrelativas.getModel();
       Materia element;
       Iterator<Materia> it = mats.iterator();
       while(it.hasNext()){
           element = it.next();
           ArrayList<Materia> correlat = element.getCorrelativas();
           if(element.getNombre() == cbCorrelativas.getSelectedItem().toString()){
              if((this.newCorrelat.stream().filter(c->c.getNombre() == cbCorrelativas.getSelectedItem().toString()).collect(Collectors.toList())).size() > 0 || (correlat.stream().filter(c->c.getNombre() == cbCorrelativas.getSelectedItem().toString()).collect(Collectors.toList())).size() > 0 ){
                   Seguidor.lanzarAlerta(cbCorrelativas.getSelectedItem().toString() + " ya forma parte de las correlativas de " + this.matActual.getNombre());
             }else{
               String[] fila = new String[3];
               fila[0] = element.getCodigo();
               fila[1] = element.getNombre();
               fila[2] = element.getNivel();
               tbAux.addRow(fila);
               this.newCorrelat.add(element);
               }
           }else{}
       }
           
    }//GEN-LAST:event_btnAddCorrelativaActionPerformed

    public void agregarRadioButtons() {
        gbModPanel.add(rbFirma);
        gbModPanel.add(rbAprob);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matModifPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matModifPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matModifPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matModifPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matModifPanel().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCorrelativa;
    private javax.swing.JButton btnModCerrar;
    private javax.swing.JButton btnModGuardar;
    private javax.swing.JComboBox<String> cbCorrelativas;
    private javax.swing.JComboBox<String> cbModNivel;
    private javax.swing.ButtonGroup gbModPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNommat;
    private javax.swing.JRadioButton rbAprob;
    private javax.swing.JRadioButton rbFirma;
    private javax.swing.JTable tbCorrelativas;
    private javax.swing.JTextField txtModCodigo;
    private javax.swing.JTextField txtModNombre;
    // End of variables declaration//GEN-END:variables
}
